### ISSUE TITLE
& Symbol appears with hex colors

### ISSUE THREAD

**Issue by NotGolden** [r4g3baby/SimpleScore#12]
Hello there, So I use your plugin for my scoreboards per world usually. I have one instance in which my hub world lists the player's rank using the Placeholder API Placeholder **vault_prefix.** However, ranks that I use with simplescore and this placeholder always have an & colored in black before the name of the rank. This only happens with ranks using hex codes. Heres an image of what I mean by this. Is there a way to fix this? LuckPerms (My permission plugin) formats hex codes using # and &. (In this case &#FF0000Sr.admin), perhaps that is the issue here, but I am not sure.
![image](https://user-images.githubusercontent.com/33296840/123044202-5bfa1200-d3c7-11eb-9a8c-65eb18a930cd.png)

**Comment by NotGolden** [comment]
I forgot to mention my versions.

Server Version: 1.16.2 
SimpleScore Version: 3.7.2

**Comment by r4g3baby** [comment]
Sorry for the late reply, this has already been fixed in the commit cb647f761c2c28995e9d0c0e3dc46d63d95c3225.
Here is a compiled version of the latest plugin dev version with this fix included: https://wormhole.app/774J8#6ar2YPTgk0uxHiHvlTFn3g
