### ISSUE TITLE
Strange client crash upon joining the server

### ISSUE THREAD

**Issue by NotGolden** [r4g3baby/SimpleScore#13]
Hey! So I just finished pre-generating a 10,000 by 10,000 block square of chunks with the Chunky Plugin. Now when I try and load into the server, I crash with this error almost every time.  The strange thing is that the default config file for SimpleScore does not crash my server, but my old one that has worked for ages does. I tried using the plugin on a second server, and my old config file works on that server with no issues. The issue only seems to happen on my first server, and not my second (test server) one. If I load my main server without the plugin installed, I do not crash upon joining the server. I am not sure if it is a plugin specific issue or something in my main server's config is causing this to happen, But I can assure that my config file works as it works on the second server without any issues, and worked on my main server until recently. If you know what this crash means, and if it is related to SimpleScore, I would appreciate it if you could get back to me. Thanks. Versions and the crash file are linked below.

Minecraft Version: 1.16.2
SimpleScore Version: 3.8.1 

`---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 6/28/21 10:42 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at afo.a(SourceFile:128)
	at dkg.a(SourceFile:47)
	at dkr.a(SourceFile:329)
	at dks.a(SourceFile:701)
	at dks.a(SourceFile:349)
	at dzr.a(SourceFile:597)
	at djw.e(SourceFile:1023)
	at djw.e(SourceFile:656)
	at net.minecraft.client.main.Main.main(SourceFile:215)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at afo.a(SourceFile:128)
	at dkg.a(SourceFile:47)
	at dkr.a(SourceFile:329)
	at dks.a(SourceFile:701)
	at dks.a(SourceFile:349)

-- Affected level --
Details:
	All players: 1 total; [dze['GoldenIsCracked'/4003, l='ClientLevel', x=-4.50, y=63.00, z=-1.50]]
	Chunk stats: Client Chunk Cache: 529, 256
	Level dimension: minecraft:lobby
	Level spawn location: World: (7,45,-51), Chunk: (at 7,2,13 in 0,-4; contains blocks 0,0,-64 to 15,255,-49), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 183422 game time, 1098000 day time
	Server brand: Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at dwl.a(SourceFile:449)
	at djw.c(SourceFile:2183)
	at djw.e(SourceFile:679)
	at net.minecraft.client.main.Main.main(SourceFile:215)

-- System Details --
Details:
	Minecraft Version: 1.16.2
	Minecraft Version ID: 1.16.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 566810136 bytes (540 MB) / 1979711488 bytes (1888 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 16
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.16.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 2060/PCIe/SSE2 GL version 4.6.0 NVIDIA 471.11, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, file/lbAlexs_Pack-V2.zip, file/QualityArmoryV2.1.8.zip
	Current Language: English (US)
	CPU: 16x AMD Ryzen 7 3700X 8-Core Processor `

**Comment by r4g3baby** [comment]
Hey, that's a strange one. Doesn't seem to be related to SimpleScore per say but just to be clear this doesn't happen if you disable SimpleScore right?

**Comment by NotGolden** [comment]
Correct. It also doesn't crash my client whenever I swap out my main config file (which runs fine on my second server) with the default one.

**Comment by r4g3baby** [comment]
Are you using a custom Minecraft client and does the server have ProtocolLib? Can you send a copy of the problematic config file.

**Comment by NotGolden** [comment]
I am not using a modded client, and yes I have the latest version of ProtocolLib. Is there a way I can send the config file privately so nobody else can possibly steal it?

**Comment by Alex-mar124** [comment]
Hey I'm the owner of the server, i can confirm that using the default config will not crash the client, but with any other it crashes, i have tried using non modded clients as well, same issue, this has no impact on the server but as soon as the score appears/renders for the player it crashes their client. Thanks For the Help!

**Comment by NotGolden** [comment]
> Hey I'm the owner of the server, i can confirm that using the default config will not crash the client, but with any other it crashes, i have tried using non modded clients as well, same issue, this has no impact on the server but as soon as the score appears/renders for the player it crashes their client. Thanks For the Help!

Right. I'm a high ranking admin / owner as well.

**Comment by r4g3baby** [comment]
> 
> 
> I am not using a modded client, and yes I have the latest version of ProtocolLib. Is there a way I can send the config file privately so nobody else can possibly steal it?

You can send me a DM on Spigot or you can add me on Discord `R4G3_BABY#0001` and send the config there.
Any chance you can try this without ProtocolLib or if you are using the latest plugin version (3.8.1) add ``ForceLegacy: true`` to the config.

**Comment by NotGolden** [comment]
I have sent you a friend request. My config file is missing that option for ForceLegacy, Maybe because we started with 3.7.2. Is it possible to add that new option to the old config file?

**Comment by NotGolden** [comment]
> > I am not using a modded client, and yes I have the latest version of ProtocolLib. Is there a way I can send the config file privately so nobody else can possibly steal it?
> 
> You can send me a DM on Spigot or you can add me on Discord `R4G3_BABY#0001` and send the config there.
> Any chance you can try this without ProtocolLib or if you are using the latest plugin version (3.8.1) add `ForceLegacy: true` to the config.

My discord tag is Golden#8079

**Comment by r4g3baby** [comment]
> 
> 
> I have sent you a friend request. My config file is missing that option for ForceLegacy, Maybe because we started with 3.7.2. Is it possible to add that new option to the old config file?

I've accepted your friend request. Yes you can add the `ForceLegacy` option and it should take effect.
I'm gonna close this issue and we can continue the discussion over on Discord.
