### ISSUE TITLE
Cant see scoreboard.

### ISSUE THREAD

**Issue by Alecs-Chan** [r4g3baby/SimpleScore#17]
/sb does not work cant see scoreboard etc. No log for it since it says there's no error.
Current MC version: 1.16.5
Current plugins are:
![Capture PNG4](https://user-images.githubusercontent.com/87970727/126957475-9aa882fb-7796-4ad4-b61e-3f6e35718d6b.PNG)

**Comment by Alecs-Chan** [comment]
[04:06:52] [Server thread/INFO]: [SimpleScore] Enabling SimpleScore v3.8.1
[04:06:53] [Server thread/INFO]: [SimpleScore] Loading disabled scoreboards...
[04:06:53] [Server thread/INFO]: [SimpleScore] Disabled scoreboards loaded.
This is all it says, but I have tried enabling it but nothing.

**Comment by Alecs-Chan** [comment]
Hmmmm I even tried messing with the worlds that can see the scoreboard and even that doesn't work.

**Comment by r4g3baby** [comment]
Please send me a full copy of your latest.log and config file.

**Comment by Alecs-Chan** [comment]
[config.txt](https://github.com/r4g3baby/SimpleScore/files/6879807/config.txt)

**Comment by Alecs-Chan** [comment]
my logs are really big and I'll have to send one later but here is the _cause_ I assume
` in 'string', line 92, column 1:
    Worlds:"survival"
    ^
could not find expected ':'
 in 'string', line 94, column 1:
    # World names are case-inse
    ^`

**Comment by r4g3baby** [comment]
The config you sent me doesn't correspond to the error you just sent.
In the error you sent it assumes there's a line with 'Worlds:"survival"' and there's no such line in the config file.

In order for me to be of any help I need the full latest.log file. You can make it smaller by restarting the server which should create a new one.

**Comment by Alecs-Chan** [comment]
I am not the original owner of the server but i have been slowly trying to fix some issues as the new owner so do not worry about some [server thread/ERROR] or [server thread/WARN] lines.
[latest.log](https://github.com/r4g3baby/SimpleScore/files/6880260/latest.log)

**Comment by r4g3baby** [comment]
There are no errors related to SimpleScore. So my best guess is you didn't specify the world name in the config file to display the scoreboard.

**Comment by Alecs-Chan** [comment]
What should I put in th bottom where the "World:" line is. To specify, how do I format it properly.
Here are the world names:
![3322](https://user-images.githubusercontent.com/87970727/127036954-6c7f8d4d-9755-46ae-871d-5d1c9fb92e3a.PNG)

**Comment by r4g3baby** [comment]
You would need to add ``survival: [ "your scoreboard name" ]`` to the bottom of the config under the Worlds section.

Closing this issue since it isn't really an issue.

**Comment by Alecs-Chan** [comment]
Thank you so much!
