### ISSUE TITLE
Cant Set the ScoreBoard in the nether or end worlds

### ISSUE THREAD

**Issue by Metaknich** [r4g3baby/SimpleScore#18]
Im triying to setup the same scoreboard that im using in the normal world in the other worlds (nether, end) i tried a lot of stuff but it never shows up , help!

**Comment by r4g3baby** [comment]
Please send me a copy of your config and latest.log files.

**Comment by Metaknich** [comment]
# Default time in ticks for a score to stay on the scoreboard (20 ticks = 1 second)
UpdateTime: 20

# Save which players have the scoreboard disabled
SaveScoreboards: true

# Whether to apply placeholders asynchronously or not
AsyncPlaceholders: true

# Enable this if you are running a 1.13+ server with backwards version support
ForceLegacy: false

# Configure your scoreboards layout
Scoreboards:
  example:
    Titles:
      - "&c&l۩Infernal Kingdom۩"
    Scores:
      18:
        - "&7&m+----------------+"
        - "&7&m------------------"
      17:
        - "&f» &9&lTu Espiritu:"
      16:
        - "    &f%player%"  
      15:
        - ""
      14:
        - "&f» &9&lTiempo Vivo:"
      13:
        - "    &f%playtime_time%"
      11:
        - ""
      10:
        - "&f» &9&lVida:"
      9:
        - "    %hearts%"
      7:
        - ""
      6:
        - "&f» &9&lProgresion:"
      5:
        - "    &fDia 0"
      4:
        - ""
      3:
        - "&f» &9&lAlmas despiertas:"
      2:
        - "    &f%online% &fAlmas"
      1:
        - "&7&m+----------------+"
        - "&7&m------------------"
  custom_time:
    Titles:
      - text: "&c100 ticks title"
        time: 100
      - text: "&a50 ticks title"
        time: 50
    Scores:
      6:
        - "&7You can set a per title or score time"
      5:
        - "&7instead of using the default value"
      4:
        - ""
      3:
        - text: "&7This will last for &810 seconds"
          time: 200
        - text: "&7while this only lasts for &85 seconds"
          time: 100
      2:
        - ""
      1:
        - "&aYour current world: &6%world%"
  restricted:
    Restricted: false
    Titles:
      - "&cRestricted Scoreboard"
    Scores:
      8:
        - ""
      7:
        - "&7Restricted scoreboards required the"
      6:
        - "&6simplescore.<scoreboard> &7permission."
      5:
        - ""
      4:
        - "&7You can see this scoreboard because"
      3:
        - "&7you have the following permission:"
      2:
        - "&6simplescore.restricted"
      1:
        - ""

# Set what scoreboards each world will be using
Worlds:
  # World names are case-insensitive
  world: [ "world_nether,wolrd_the_end" ]
  # This will match all worlds starting with "world_" (e.g. world_nether, world_the_end)
  world_\w*: [ "world_" ]
  # If player doesn't have permission to see the restricted scoreboard then it will display the example
  multiple: [ "restricted", "example" ]

**Comment by Metaknich** [comment]
This is my config

**Comment by r4g3baby** [comment]
``world: [ "world_nether,wolrd_the_end" ]`` this isn't right. To the left is where you put the name of your worlds and to the right is the list of scoreboards to display.

Closing this issue since it isn't really and issue. For support please use the Spigot Discussion/DMs or Discord.
