### ISSUE TITLE
Scoreboard is getting cutoff when using ViaVersion for clients on <1.13 versions

### ISSUE THREAD

**Issue by Anim3Add1ct** [r4g3baby/SimpleScore#19]
Hi, I'm running on Paper 1.17.1 and SimpleScore version 3.8.1. There are players experiencing this:

![image](https://user-images.githubusercontent.com/87047558/127791295-a5a9a750-d7dc-4314-94da-c864b531e2d9.png)

But, my scoreboard displays everything correctly, as such:

![2021-08-02_08 59 30](https://user-images.githubusercontent.com/87047558/127791351-8e79c275-3e36-45de-9e2f-6a4b7077c4e3.png)

I have PlaceholderAPI (v2.10.10) and ProtocolLib (v4.7.0) installed.

**Comment by r4g3baby** [comment]
Hey, are said players running on a lower/different minecraft version from the server? (This issue usually happens on servers running ViaVersion/ProtocolSupport).

**Comment by Anim3Add1ct** [comment]
Oh, that is probably the case, I didn't ask the player. Is there a way to fix this for lower/different versions?

**Comment by r4g3baby** [comment]
Setting ``ForceLegacy`` to ``true`` should fix the issue, however you will no longer be able to use unlimited characters per line (you will be limited to 32 if I'm not mistaken) and hex colors.

**Comment by Anim3Add1ct** [comment]
Oh that's quite a trade-off. Thanks for the quick support. :D

**Comment by r4g3baby** [comment]
I have done a few changes that should improve compatibility with ViaVersion, if you have the time you can either compile the plugin main branch or download this already compiled version of the repo https://wormhole.app/qlzmJ#2wS60XbMp6Yw8jENitEX8Q

I haven't had the time to properly test it yet but once I do and if everything is working fine I'll release a new version on spigot.
