### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by UniqueJohnn** [r4g3baby/SimpleScore#20]
hello, how can i enable the scorebord on all worlds that I have?

i believe this area?

Worlds:
  # World names are case-insensitive
  world: [ "example" ]
  # This will match all worlds starting with "world_" (e.g. world_nether, world_the_end)
  world_\w*: [ "custom_time" ]
  # If player doesn't have permission to see the restricted scoreboard then it will display the example
  multiple: [ "restricted", "example" ]

**Comment by r4g3baby** [comment]
You can use regex, ``\w*: [ "your scoreboard name" ]``. Please only use GitHub issues for actual issues, for support use Spigot DMs or Discord.
