### ISSUE TITLE
Sidebar Scoreboard will not display, nothing in logs.

### ISSUE THREAD

**Issue by jackgraddon** [r4g3baby/SimpleScore#21]
Just downloaded the plugin and installed it, but the sidebar doesn't actually display. The commands work and all, but the sidebar just doesn't display. Nothing in logs to give any clue why it doesn't display, unsure of what is causing the issue. If you need any info I can get it.

Running Paper 1.16.5

**Comment by r4g3baby** [comment]
Hey, did you check the configuration to make sure your current world is defined in there?

**Comment by jackgraddon** [comment]
That is what those are for, so sorry. Not sure why I was so confused by this config file, but it just all clicked. It was late, thank you!
