### ISSUE TITLE
Where is gradients?

### ISSUE THREAD

**Issue by borodin0v** [r4g3baby/SimpleScore#22]

**Comment by r4g3baby** [comment]
Hey, please be more specific. What are you trying to do/what do you expect to see?

**Comment by borodin0v** [comment]
If my server prefixes has PREFIX with gradient (1.16 hex), e.g. "<#FFAAFF>Moder</#FFBBAA>", how I can implement this in my scoreboard?

**Comment by r4g3baby** [comment]
Hex colors get automatically converted and should just work out of the box. So something like `&#ffffff` will assume the white color.

**Comment by borodin0v** [comment]
Thanks.
