### ISSUE TITLE
placeholder

### ISSUE THREAD

**Issue by husosh** [r4g3baby/SimpleScore#3]
when i use the placeholder %luckperms_prefix% and use hex colour codes in the prefix this happens:

![Screenshot 2020-12-10 at 21 36 40](https://user-images.githubusercontent.com/61317838/101832979-3b0b5700-3b30-11eb-88cc-5f39f83b8ae6.png)

**Comment by r4g3baby** [comment]
Hex color codes aren't supported on scoreboards as far as I'm aware.

**Comment by r4g3baby** [comment]
As far as I'm aware there is no way to support this, feel free to reopen if you think otherwise.
