### ISSUE TITLE
%cmi_equationint_<expression>% does not work

### ISSUE THREAD

**Issue by SbirTeo** [r4g3baby/SimpleScore#31]
I want to use this format in conditions:

candiotionName:
  type: EQUALS
  input: '%cmi_equationint_{bedwars_game_test_minplayers}-{bedwars_game_test_players}%'
  value: '0'
  
  but it's not working

**Comment by r4g3baby** [comment]
Hey, what's the output if you run ``/papi parse me %cmi_equationint_{bedwars_game_test_minplayers}-{bedwars_game_test_players}%`` in-game?

**Comment by SbirTeo** [comment]
Close please. I'm wrong. It works fine. Im sorry.
