### ISSUE TITLE
Scoreboard lines issue

### ISSUE THREAD

**Issue by Bilal380870** [r4g3baby/SimpleScore#32]
Hello @r4g3baby i configured a scoreboard of 17 lines but ingame it shows only 14 lines mean it starts from 2 and ends on 16.
Here is scoreboard value:
simple2:
  titles: '&a&lHypo&f&lCraft'
  scores:
    16:
      - '&7&m+----------------+'
      - '&7&m------------------'
    15: '&7» &4&l⭐&b&lPlayer'
    14: '     &f%player%'
    13: ''
    12: '&7» &4&l⭐&b&lHealth'
    11: '     %hearts%'
    10: ''
    9: '&7» &4&l⭐&b&lRank'
    8: '     &f%luckperms_prefix%'
    7: ''
    6: '&7» &4&l⭐&b&lBalance'
    5: '     &f%vault_eco_balance_fixed%$'
    4: ''
    3: '&7» &4&l⭐&b&lPlaytime'
    2: '     &f%playtime_time%'
    1: 
     - '&7&m+----------------+'
     - '&7&m------------------'
     
     Here is the output of scoreboard in minecraft:
     
![09](https://user-images.githubusercontent.com/77220937/152684511-eac5f43a-6a8c-4c6b-8748-0c74b975e15c.PNG)

**Comment by r4g3baby** [comment]
Hey, this is not an issue with SimpleScore. The vanilla Minecraft client only renders 15 scoreboard lines.
