### ISSUE TITLE
Citizens support

### ISSUE THREAD

**Issue by rudde0** [r4g3baby/SimpleScore#34]
I think SimpleScore creates scoreboard too for citizens NPCs. Just try to spam few NPCs and check console.

Thanks.

**Comment by r4g3baby** [comment]
Hey, could you please elaborate. How is this an issue, is there any sort of error in the console because of this behaviour?

**Comment by rudde0** [comment]
There are placeholder API access warnings. Warnings are coming from SimpleScore plugin. SimpleScore should check for metadata "NPC" of players. If player has metadata such as this tag, plugin must skip the player.

**Comment by r4g3baby** [comment]
I'll look into it. I've never used Citizens before but that is somewhat strange behaviour because it would mean that Citizens is adding actual player objects to the server player registry.
Are you aware of some Citizens documentation for this behaviour so I don't have to waste time searching for it? It would be of great help.

**Comment by rudde0** [comment]
https://wiki.citizensnpcs.co/API


This variable will create exception for the player NPCs:
`boolean isCitizensNPC = entity.hasMetadata("NPC");`

**Comment by r4g3baby** [comment]
Thanks, I've added this to a development version, would you be willing to test it if I send you a compiled version of the plugin?

**Comment by rudde0** [comment]
Sure

**Comment by r4g3baby** [comment]
Here it goes, please let me know if this fixes it.

https://wormhole.app/v0ZYM#uWJWqGfW72j4UzKq7R4zrg

**Comment by rudde0** [comment]
This dev version fixed this issue. Thanks a lot. <3

**Comment by r4g3baby** [comment]
No problem, thanks for taking the time to suggest and help test it!
