### ISSUE TITLE
Feature request: add MineDown (essentially for ProtocolLib boards)

### ISSUE THREAD

**Issue by borodin0v** [r4g3baby/SimpleScore#35]
MineDown is a library inspired by markdown that allows to do things like this: this text [Hi](color=#fff-#000 HoverText) displays a gradient from #ffffff to #000000 and a hover text of "HoverText"

**Comment by r4g3baby** [comment]
Hey, thanks for the suggestion but I won't be adding this. Most of this features are already supported by PlaceholderAPI and it can also be achieved using other external tools.
