### ISSUE TITLE
Limit of characters

### ISSUE THREAD

**Issue by ismelou** [r4g3baby/SimpleScore#36]
Hello. I have placeholders with big colors code, but the plugin have a limit of characters.

-----------------------------------------------------------------------------------------------

simple:
  titles: '&#ee8500&lS&#dd7b00&lu&#cc7000&lr&#bb6600&lv&#aa5b00&li&#995100&lv&#884600&lal'
  scores:
    13: '&r'
    12: '  &6⛏ &fRank: &7%luckperms_prefix%'
    11: '  &#DCE35B⛁ &fSaldo: &a%vault_eco_balance_formatted%'
    10: ''
    9: '  &#D00B65♥ &fStatus&7: &a%marriagemaster_IsMarried%'
    8: '  &c⚔ &fClan&7: &7%simpleclans_clan_color_tag%'
    7: ''
    6: '  &d☆ &fPinhata&7: &5%pinataparty_current_votes%&8/&5%pinataparty_votes_needed%'
    1: ''

-----------------------------------------------------------------------------------------------

See the rank on image
https://prnt.sc/_LWlwWq3VkvS

**Comment by r4g3baby** [comment]
Hey, what version is your server running?

**Comment by ismelou** [comment]
Minecraft Purpur 1.18.1
Last plugin version

**Comment by r4g3baby** [comment]
By last plugin version I assume you mean 3.10.1 correct?
Do you have ProtocolLib on your server and are you running ViaVersion/ViaBackwards (or anything that adds multiple version support)?

**Comment by ismelou** [comment]
Yes, 3.10.1.
Yes, I have ProtocolLib.
Yes, I have ViaBackwards and ViaVersion 4.1.1

**Comment by r4g3baby** [comment]
And what version is your client running on?

**Comment by ismelou** [comment]
My client is the native version? 
Native version: 1.18.1

**Comment by r4g3baby** [comment]
Interesting, and are you using the vanilla client or do you have any mods installed (e.g. Optifine, Fabric, Forge, Lunar Client, etc)?

**Comment by ismelou** [comment]
Im using Optifine 1.18.1
Another players see scoreboard with the limit of characters too

**Comment by r4g3baby** [comment]
Ok, can you send me the output of the variable ``%luckperms_prefix%`` so I can test this locally.

**Comment by ismelou** [comment]
%luckperms_prefix% for me >>> &#a3025a[&l&#930264&lD&r&#83026do&#730177n&#630180o&#53018a]&r

Obs.: If I place a word with a big color code on title of score, the word is also cut.

**Comment by ismelou** [comment]
Ok

**Comment by r4g3baby** [comment]
The commit 21a1688 should alleviate this issue. I'll be releasing a new version on spigot probably by the end of the week.

If you are running a server with ViaBackwards or ``forceMultiVersion`` enabled your character limit will be the following:
On 1.12 and bellow: 32 characters
On 1.13 and above: 80 characters (players bellow 1.13 will still only be able to see 32 characters)

If you don't have ViaBackwards (or ``ignoreViaBackwards`` is enabled) and ``forceMultiVersion`` is disabled:
On 1.12 and bellow: 32 characters
On 1.13 and above: 128 characters

Keep in mind each hex color is the same as having 14 characters and can make you reach the maximum amount of characters very quickly.

**Comment by r4g3baby** [comment]
Hey, after taking another look at this I realized I was applying an unnecessary limit of characters for servers on 1.13 and newer (that is if you have ProtocolLib). Commit faf1723 fixes that, I'll be releasing an update on Spigot tomorrow.

Just to be clear if you don't have ProtocolLib or are on 1.12 and older you will still be limited to the same limits I specified above.
