### ISSUE TITLE
Scoreboard disappears for everyone who rejoins the server

### ISSUE THREAD

**Issue by sadboiKYLE** [r4g3baby/SimpleScore#37]
I'm using TAB and SimpleScore plugins (and a bunch more but I feel like the issue's caused by one of these two). Pretty much after each server restart the scoreboard works perfect, but when anyone relogs, they can't see the scoreboard anymore. I try to untoggle and toggle the scoreboard, doesn't work, and I also try to reload the plugin, which doesn't work. Any suggestions?

**Comment by sadboiKYLE** [comment]
Yes I do, what do I change?

**Comment by r4g3baby** [comment]
This is a known issue and has already been fixed in the latest commit (a3f6947). There is no current workaround besides compiling the current build of the plugin or waiting for me to make a release on spigot.
