### ISSUE TITLE
Spam Of Errors

### ISSUE THREAD

**Issue by paolosasso** [r4g3baby/SimpleScore#39]
I am using the lastest version of the plugin and 1.17, this is the console, I don't really know where to look into
[latest (1).log](https://github.com/r4g3baby/SimpleScore/files/8336635/latest.1.log)
These are the scoreboards.yml
https://mclo.gs/iv8r4Bd

**Comment by r4g3baby** [comment]
Hey, this is a problem with one of your placeholders and SimpleScore itself. You will need to figure out what placeholder is causing this issue and either remove it or find a way to fix it.
If I had to guess I'd say the problem comes from the ``javascript`` placeholders.
