### ISSUE TITLE
Bad Timings

### ISSUE THREAD

**Issue by KhrysAK47** [r4g3baby/SimpleScore#4]
Server TPS drop, cause is SimpleScore, any ideas?

https://timings.aikar.co/?id=5f64b4c285ae4a6890710c5ba9b677bb

**Comment by r4g3baby** [comment]
Can you send me a copy of your config file please.

**Comment by KhrysAK47** [comment]
https://pastebin.com/mAPwiSY5

**Comment by r4g3baby** [comment]
Sorry for the late reply, could you try it without placeholders and let me know if that reduces the TPS impact.

**Comment by KhrysAK47** [comment]
Huh? like without any placeholders?.

**Comment by r4g3baby** [comment]
Yeah, just so we can see if the problem comes from the placeholders.

**Comment by KhrysAK47** [comment]
Issue still persists after having no placeholders there

**Comment by r4g3baby** [comment]
Ok that's weird, any chance you can add the spark (https://github.com/lucko/spark) plugin to your server and run the CPU profiler.
That might give us some more useful information as to what's causing the high usage.

**Comment by KhrysAK47** [comment]
Sure, will do and let you know, also, is there a way you can give me your discord instead of communicating via Github every time? Faster and easier haha

**Comment by r4g3baby** [comment]
Yeah for sure, feel free to add me. My username is R4G3_BABY#0001.

**Comment by KhrysAK47** [comment]
Thanks! Just added you. :)
