### ISSUE TITLE
Option to make scoreboard toggle on when joining server.

### ISSUE THREAD

**Issue by Klawdek** [r4g3baby/SimpleScore#54]
It would be nice to have an option to cause the scoreboard to toggle on when joining server.  So if it was turned off it would turn on again.  Otherwise layers turn it off and forget it is there.

**Comment by r4g3baby** [comment]
Hey, sorry for the late reply but you can set the storage driver option to none, this will disable player data saving and thus the scoreboard will always show up when players rejoin the server.
