### ISSUE TITLE
I cant see the scoreboard?

### ISSUE THREAD

**Issue by Jez44** [r4g3baby/SimpleScore#60]
Scoreboard.yml:
## Scoreboards (https://github.com/r4g3baby/SimpleScore/blob/main/src/main/resources/scoreboards.yml)
# This is where you create your scoreboards to be displayed.

# You can create a scoreboard by creating a node with the scoreboard name and then specifying a default "updateTime",
#  "renderTime" and a list of "titles" and "scores".
#
# "updateTime": the default update time in ticks (optional and defaults to 20 ticks/1 second)
#  This controls how long it takes for each frame to stay on the scoreboard
# "renderTime": the default render time in ticks (optional and defaults to 10 ticks/0.5 seconds)
#  This controls how long it takes before rendering each frame, placeholders and variables will only get applied each
#   time a render occurs (the lower the render time is the heavier it will be on server performance)
# "titles": text to display or a list of frames*
# "scores": the score number/value followed by the text to display or a list of frames* or a map with the "conditions"
#  (list of conditions*) and "frames" (list of frames*) keys
#
# *conditions: can be prefixed with a "!" (exclamation mark) to negate the condition
# *frames: is a list of strings or list of maps with the "text" (text to display),
#  "update" (time to stay visible, optional and defaults to "updateTime") and
#  "render" (time to wait before rendering, optional and defaults to "renderTime") keys
#
# Check out the examples bellow for more information.

# This is a simple scoreboard with only the top and bottom lines animated
simple:
  titles: '&7&LYour&6&lServer'
    12: ''
    11: '&7%player%'
    10: '&a$ &fBalance: &a$%vault_eco_balance_commas%'
    9: '&c❤ &fHearts: &c%player_max_health%'
    8: '&6⚔ &fTeam: &6%betterTeams_displayname%'
    7: '&b⏳ &fPlaytime: &b%statistic_hours_played%h'
    6: ''
    5: '&c🗡 &fKills: &4%statistic_player_kills%'
    4: '&c☠ &fDeaths: &4%statistic_deaths%'
    3: '&c⚔ &fK/D: &40.0'
    2: ''
    1: '&7⛏ play.jezmc.com'

Plugins:
![Screenshot (203)](https://github.com/r4g3baby/SimpleScore/assets/133359233/7736d999-9f3c-454c-bed4-9794f3a45e91)

**Comment by deltatron7543** [comment]
did you try toggling the scoreboard? and paste that in a code block, you should have noticed that when you pasted it, either way next time please use the code block when pasting code or even logs I would say
