### ISSUE TITLE
showing same score board in two world

### ISSUE THREAD

**Issue by Katta01** [r4g3baby/SimpleScore#62]
hlo i have install simple score board plugin and i have different world like superiorworld , world , skyblock , lifesteal and i have diffrent score board on diffrent world but in superiorworld and world they are showing same scoreboard can anyone help

**Comment by Katta01** [comment]
worlds:
  # If player doesn't meet the conditions to see the conditional scoreboard then it will display the simple scoreboard
  world_the_end: [ 'conditional', 'simple' ]
  # This will match all worlds starting with "world_" (e.g. world_nether, world_the_end)
  # "world_the_end" will never reach this line since it already matched above
  world_\w*: [ 'customTiming' ]
  # This will match all worlds that haven't been defined above
  '[Lobby ]*': [ 'simple' ]
  '[LifeSteal ]*': [ 'LifeSteal' ]
  '[SkyBlock ]*': [ 'SKYBLOCK' ]
  '[SuperiorWorld ]*': [ 'SKYBLOCK' ]
  '[LifeStealLObby ]*': [ 'LifeSteal' ]
  '[world ]*': [ 'WORLD' ]
  
  
  
  ----
  
  # This is a simple scoreboard with only the top and bottom lines animated
simple:
  titles: '&7&LREUNION&6&lSERVER'
  scores:
    13:
      - '&7&m+----------------+'
      - '&7&m------------------'
    12: '&7» &6&lPlayer'
    11: '    &7%player%'
    10: ''
    9: '&7» &6&lHealth'
    8: '    %hearts%'
    7: ''
    6: '&7» &6&lWorld'
    5: '    &7%world%'
    4: ''
    3: '&7» &6&lOnline Players'
    2: '    &7%online% &6players'
    1:
      - '&7&m+----------------+'
      - '&7&m------------------'

LifeSteal:
  titles: '&7&LLIFE&6&lSTEAL'
  scores:
    13:
      - '&7&m+----------------+'
      - '&7&m------------------'
    12: '&7» &6&lPlayer'
    11: '    &7%player%'
    10: ''
    9: '&7» &6&lHealth'
    8: '    %hearts%'
    7: ''
    6: '&7» &6&lWorld'
    5: '    &7%world%'
    4: ''
    3: '&7» &6&lOnline Players'
    2: '    &7%online% &6players'
    1:
      - '&7&m+----------------+'
      - '&7&m------------------'      

SKYBLOCK:
  titles: '&7&LSKY&6&lBLOCK'
  scores:
    13:
      - '&7&m+----------------+'
      - '&7&m------------------'
    12: '&7» &e&l✌ Name'
    11: '    &6%player%'
    10: ''
    9: '&7» &e&l✯ Rank'
    8: '    &6%luckperms_prefix%'
    7: ''
    6: '&7» &e&l⛏ Island Level'
    5: '    &6%superior_island_level%'
    4: ''
    3: ' &7» &e&l$ Money'
    2: '   &b &6%vault_eco_balance_formatted%'
    1:
      - '&7&m+----------------+'
      - '&7&m------------------'      

WORLD:
  titles: '&7&LUKY&6&lBLOCK'
  scores:
    13:
      - '&7&m+----------------+'
      - '&7&m------------------'
    12: '&7» &e&l✌ Name'
    11: '    &6%player%'
    10: ''
    9: '&7» &e&l✯ Rank'
    8: '    &6%luckperms_prefix%'
    7: ''
    6: '&7» &e&l⛏ Island Level'
    5: '    &6%superior_island_level%'
    4: ''
    3: ' &7» &e&l$ Money'
    2: '   &b &6%vault_eco_balance_formatted%'
    1:
      - '&7&m+----------------+'
      - '&7&m------------------'

**Comment by r4g3baby** [comment]
Use [Discord ](https://discord.gg/cJnzTDGphE)for help configuring the plugin. GitHub issues are only for bug reports and feature requests.
