### ISSUE TITLE
so how can i fix this 

### ISSUE THREAD

**Issue by Katta01** [r4g3baby/SimpleScore#63]
worlds:

If player doesn't meet the conditions to see the conditional scoreboard then it will display the simple scoreboard
world_the_end: [ 'conditional', 'simple' ]

This will match all worlds starting with "world_" (e.g. world_nether, world_the_end)
"world_the_end" will never reach this line since it already matched above
world_\w*: [ 'customTiming' ]

This will match all worlds that haven't been defined above
'[Lobby ]': [ 'simple' ]
'[LifeSteal ]': [ 'LifeSteal' ]
'[SkyBlock ]': [ 'SKYBLOCK' ]
'[SuperiorWorld ]': [ 'SKYBLOCK' ]
'[LifeStealLObby ]': [ 'LifeSteal' ]
'[world ]': [ 'WORLD' ]

**Comment by r4g3baby** [comment]
Use [Discord ](https://discord.gg/cJnzTDGphE)for help configuring the plugin. GitHub issues are only for bug reports and feature requests.
