### ISSUE TITLE
Dead counters

### ISSUE THREAD

**Issue by kleineTorte** [r4g3baby/SimpleScore#70]
### Feature Description

A death counter appears on the scoreboard When you die, the current deaths are shown And there should be a way to call up the dead of any player with one command However, only the person who executes this command should see this list

### Feature Goal

that every player can see their dead for themselves

### Unfitting Alternatives

There was no alternative as far as I know

**Comment by r4g3baby** [comment]
Hi! Thanks for taking the time to open this issue but this is out of scope for this plugin.
You can already show a death count on your scoreboard by using PlaceholderAPI and one of their extensions that provides a placeholder for player deaths either via statistics or a specific plugin that keeps track of this.
