### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Shucai99** [r4g3baby/SimpleScore#8]
i download your  pl and don t have a scorebord idk why i got all neu but don t work thx 4 help

**Comment by r4g3baby** [comment]
Hey, make sure you configure the plugin to work with your current worlds. If you already have done that and still doesn't work please provide a copy of your config file and latest.log.

**Comment by r4g3baby** [comment]
I'll assume your issue has been fixed, if not feel free to re-open the issue.
